version: '3.3'
services:
    boost-bot:
        image: boost-bot
        command: brownie run scripts/rewards/propose_boost.py --network=mainnet
        build: 
            context: .
            dockerfile: Dockerfile