apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: approve-arb-cycle-bot
  labels:
    app: approve-arb-cycle-bot
spec:
  schedule: "15 18 * * *"
  startingDeadlineSeconds: 180
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: approve-arb-cycle-bot
          containers:
          - name: approve-arb-cycle-bot
            image: IMAGE_NAME
            imagePullPolicy: IfNotPresent
            command: ["python", "-m", "scripts.rewards.arbitrum.manual_arb_cycle_approve"]
            env:
              - name: LOG_LEVEL
                value: 'info'
              - name: TEST
                value: 'False'
              - name: KUBE
                value: 'True'
          restartPolicy: OnFailure