apiVersion: batch/v1beta1
kind: CronJob
metadata:
    name: approve-arb-cycle-bot
    labels:
        app: approve-arb-cycle-bot
spec:
    schedule: '25 20 * * *'
    startingDeadlineSeconds: 180
    suspend: false
    jobTemplate:
        spec:
            template:
                spec:
                    serviceAccountName: approve-arb-cycle-bot
                    containers:
                        - name: approve-arb-cycle-bot
                          image: IMAGE_NAME
                          imagePullPolicy: IfNotPresent
                          command: ['python', '-m', 'scripts.rewards.arbitrum.approve_arbitrum']
                          env:
                              - name: LOG_LEVEL
                                value: 'info'
                              - name: ENV
                                value: 'PROD'
                              - name: KUBE
                                value: 'True'
                              - name: 'FIX_CYCLE'
                                value: 'True'
                    restartPolicy: OnFailure
