apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: approve-poly-cycle-bot
  labels:
    app: approve-poly-cycle-bot
spec:
  schedule: "30 */2 * * *"
  startingDeadlineSeconds: 180
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: approve-poly-cycle-bot
          containers:
          - name: approve-poly-cycle-bot
            image: IMAGE_NAME
            imagePullPolicy: IfNotPresent
            command: ["python", "-m", "scripts.rewards.polygon.approve_polygon"]
            env:
              - name: LOG_LEVEL
                value: 'info'
              - name: ENV
                value: 'PROD'
              - name: KUBE
                value: 'True'
          restartPolicy: OnFailure
