apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: boost-bot
  labels:
    app: boost-bot
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: boost-bot
          containers:
          - name: boost-bot
            image: IMAGE_NAME
            imagePullPolicy: IfNotPresent
            command: ["brownie", "run", "scripts/rewards/propose_boost.py", "--network=mainnet"]
            env:
              - name: LOG_LEVEL
                value: 'info'
              - name: TEST
                value: 'True'
          restartPolicy: OnFailure
