apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: boost-bot
  labels:
    app: boost-bot
spec:
  schedule: "*/10 * * * *"
  startingDeadlineSeconds: 180
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: boost-bot
          containers:
          - name: boost-bot
            image: IMAGE_NAME
            imagePullPolicy: IfNotPresent
            command: ["python", "-m", "scripts.rewards.propose_boost"]
            env:
              - name: LOG_LEVEL
                value: 'info'
              - name: TEST
                value: 'False'
          restartPolicy: OnFailure
