apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: boost-bot
  labels:
    app: boost-bot
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: boost-bot
          containers:
          - name: boost-bot
            image: IMAGE_NAME
            imagePullPolicy: IfNotPresent
            command: [ 
              'export', 'WEB3_INFURA_PROJECT_ID=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-west-1:342684350154:secret:boost-bot/infura-id-zb9i9o | jq -r ".SecretString" | jq -r ".INFURA_ID")', 
              '&&', 'brownie', 'run', 'scripts/rewards/propose_boost.py', '--network=mainnet'
            ]
            env:
              - name: LOG_LEVEL
                value: 'info'
              - name: TEST
                value: 'True'
          restartPolicy: OnFailure
