apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: eth-boost-bot
  labels:
    app: eth-boost-bot
spec:
  schedule: "*/20 * * * *"
  startingDeadlineSeconds: 180
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: eth-boost-bot
          containers:
          - name: eth-boost-bot
            image: IMAGE_NAME
            imagePullPolicy: IfNotPresent
            command: ["python", "-m", "scripts.rewards.boost_eth"]
            env:
              - name: LOG_LEVEL
                value: 'info'
              - name: TEST
                value: 'True'
              - name: KUBE
                value: 'True'
          restartPolicy: OnFailure
