apiVersion: batch/v1beta1
kind: CronJob
metadata:
    name: propose-eth-cycle-bot
    labels:
        app: propose-eth-cycle-bot
spec:
    schedule: '30 15 * * *'
    startingDeadlineSeconds: 180
    suspend: false
    jobTemplate:
        spec:
            template:
                spec:
                    serviceAccountName: propose-eth-cycle-bot
                    containers:
                        - name: propose-eth-cycle-bot
                          image: IMAGE_NAME
                          imagePullPolicy: IfNotPresent
                          command: ['python', '-m', 'scripts.rewards.ibbtc_rewards.propose']
                          env:
                              - name: LOG_LEVEL
                                value: 'info'
                              - name: ENV
                                value: 'PROD'
                              - name: KUBE
                                value: 'True'
                          resources:
                              requests:
                                  memory: '2000m'
                                  cpu: '500m'
                    restartPolicy: OnFailure
