apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: propose-eth-cycle-bot
  labels:
    app: propose-eth-cycle-bot
spec:
  schedule: "22 22 * * *"
  startingDeadlineSeconds: 180
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: propose-eth-cycle-bot
          containers:
          - name: propose-eth-cycle-bot
            image: IMAGE_NAME
            imagePullPolicy: IfNotPresent
            command: ["python", "-m", "scripts.rewards.eth.propose_eth"]
            env:
              - name: LOG_LEVEL
                value: 'info'
              - name: TEST
                value: 'False'
              - name: KUBE
                value: 'True'
          restartPolicy: OnFailure
