apiVersion: batch/v1beta1
kind: CronJob
metadata:
    name: propose-arb-cycle-bot
    labels:
        app: propose-arb-cycle-bot
spec:
    schedule: '35 3 * * *'
    startingDeadlineSeconds: 180
    suspend: false
    jobTemplate:
        spec:
            template:
                spec:
                    serviceAccountName: propose-arb-cycle-bot
                    containers:
                        - name: propose-arb-cycle-bot
                          image: IMAGE_NAME
                          imagePullPolicy: IfNotPresent
                          command: ['python', '-m', 'scripts.rewards.fix_cycle.fix_arb']
                          env:
                              - name: LOG_LEVEL
                                value: 'info'
                              - name: ENV
                                value: 'PROD'
                              - name: KUBE
                                value: 'True'
                    restartPolicy: OnFailure
