apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: propose-eth-cycle-bot
  labels:
    app: propose-eth-cycle-bot
spec:
  schedule: "5 19 * * 4"
  startingDeadlineSeconds: 180
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: propose-eth-cycle-bot
          containers:
          - name: propose-eth-cycle-bot
            image: IMAGE_NAME
            imagePullPolicy: IfNotPresent
            command: ["python", "-m", "scripts.rewards.fix_cycle.fix_eth_propose"]
            env:
              - name: LOG_LEVEL
                value: 'info'
              - name: ENV
                value: 'PROD'
              - name: KUBE
                value: 'True'
          restartPolicy: OnFailure
