apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: propose-ftm-cycle-bot
  labels:
    app: propose-ftm-cycle-bot
spec:
  schedule: "35 1 * * *"
  startingDeadlineSeconds: 180
  suspend: False
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: propose-ftm-cycle-bot
          containers:
          - name: propose-ftm-cycle-bot
            image: IMAGE_NAME
            imagePullPolicy: IfNotPresent
            command: ["python", "-m", "scripts.rewards.fantom.propose_fantom"]
            env:
              - name: LOG_LEVEL
                value: 'info'
              - name: ENV
                value: 'PROD'
              - name: KUBE
                value: 'True'
              - name: 'FIX_CYCLE'
                value: 'True'
          restartPolicy: OnFailure
