apiVersion: v1
kind: ServiceAccount
metadata:
  name: boost-bot
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::342684350154:role/boost-bot
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  propose-poly-cycle-bot
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::342684350154:role/propose-poly-cycle-bot
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: approve-poly-cycle-bot
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::342684350154:role/approve-poly-cycle-bot
---