apiVersion: v1
kind: Service
metadata:
  name: boost-bot
  labels:
    app: boost-bot
    service: boost-bot
spec:
  selector:
    app: boost-bot
  ports:
    - name: http
      port: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: propose-poly-cycle-bot
  labels:
    app: propose-poly-cycle-bot
    service: propose-poly-cycle-bot
spec:
  selector:
    app: propose-poly-cycle-bot
  ports:
    - name: http
      port: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: approve-poly-cycle-bot
  labels:
    app: approve-poly-cycle-bot
    service: approve-poly-cycle-bot
spec:
  selector:
    app: approve-poly-cycle-bot
  ports:
    - name: http
      port: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: propose-arb-cycle-bot
  labels:
    app: propose-arb-cycle-bot
    service: propose-arb-cycle-bot
spec:
  selector:
    app: propose-arb-cycle-bot
  ports:
    - name: http
      port: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: approve-arb-cycle-bot
  labels:
    app: approve-arb-cycle-bot
    service: approve-arb-cycle-bot
spec:
  selector:
    app: approve-arb-cycle-bot
  ports:
    - name: http
      port: 9000
---