apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-read
subjects:
- kind: ServiceAccount
  name: arb-boost-bot-stg
- kind: ServiceAccount
  name: eth-boost-bot-stg
- kind: ServiceAccount
  name: poly-boost-bot-stg
