apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: poly-boost-bot-stg
  labels:
    app: poly-boost-bot-stg
spec:
  schedule: "*/20 * * * *"
  startingDeadlineSeconds: 180
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: poly-boost-bot-stg
          containers:
          - name: poly-boost-bot-stg
            image: IMAGE_NAME
            imagePullPolicy: IfNotPresent
            command: ["python", "-m", "scripts.rewards.boost.boost_polygon"]
            env:
              - name: LOG_LEVEL
                value: 'info'
              - name: ENV
                value: 'STG'
              - name: KUBE
                value: 'True'
          - name: fluent-bit
            image: public.ecr.aws/aws-observability/aws-for-fluent-bit:stable
            imagePullPolicy: Always
            volumeMounts:
            - name: fluentbitconfigvol
              mountPath: /etc/fluent-bit/conf/
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            command: ["/fluent-bit/bin/fluent-bit"]
            args: ["-c", "/etc/fluent-bit/conf/fluent-bit.conf"]
          volumes:
          - name: fluentbitconfigvol
            configMap:
              name: fluent-bit-config
          - name: varlog
            emptyDir: {}
          - name: varlibdockercontainers
            emptyDir: {}
          restartPolicy: OnFailure
