apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: poly-boost-bot-stg
  labels:
    app: poly-boost-bot-stg
spec:
  schedule: "*/20 * * * *"
  startingDeadlineSeconds: 180
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: poly-boost-bot-stg
          containers:
          - name: poly-boost-bot-stg
            image: IMAGE_NAME
            imagePullPolicy: IfNotPresent
            command: ["python", "-m", "scripts.rewards.boost_polygon"]
            env:
              - name: LOG_LEVEL
                value: 'info'
              - name: TEST
                value: 'True'
              - name: KUBE
                value: 'True'
          restartPolicy: OnFailure
